baseURL = "http://notes.pbe9216.com/"
title = "My notes"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
geekdocMenuBundle = true
geekdocBreadcrumb = true
geekdocNextPrev = false
geekdocBackToTop = true
geekdocDarkModeDim = true


[taxonomies]
   tag = "tags"

[params.geekdocContentLicense]
name = "CC BY-SA 4.0"
link = "https://creativecommons.org/licenses/by-sa/4.0/"